[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "zern"
version = "0.0.21"
authors = [
  { name="Harsha Avapati", email="harshaavapati@gmail.com" },
]
description = "An unofficial client library using Zerodha web api for live data and historical data"
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
  "websocket-client",
  "pyotp",
  "requests",
  "certifi",
  "numpy"
]

[project.urls]
Homepage = "https://github.com/ExBlacklight/Zern"
Issues = "https://github.com/ExBlacklight/Zern/issues"
